// src/common/pdf/pdf.util.ts
//
// NEW_Changes item 10 — real, downloadable PDF documents (invoice, Goods
// Receipt Note, Gate Out Pass), generated server-side with pdfkit (pure
// JS, no native/Chromium dependency, so it works in any Node
// environment). One shared layout function covers all three document
// types — they're structurally the same shape (header, from/to, meta
// rows, a line-item table, a total) — rather than three near-duplicate
// renderers that would drift apart over time.
import * as PDFDocument from 'pdfkit';

export interface PdfLineItem {
  label: string;
  amount?: number; // omit for a plain informational row with no amount column
}

export interface PdfDocumentSpec {
  documentTitle: string; // e.g. "STORAGE INVOICE"
  documentNumber: string; // e.g. "INV-2026-000001"
  issuedAt: Date;
  fromLines: string[];
  toLines: string[];
  meta?: [string, string][]; // extra key/value rows above the table (booking ref, commodity, etc.)
  lineItems: PdfLineItem[];
  totalLabel?: string;
  totalAmount?: number;
  footerNote?: string;
}

const BRAND_GREEN = '#15803D';
const PAGE_LEFT = 50;
const PAGE_RIGHT = 545;

export function renderPdfDocument(spec: PdfDocumentSpec): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Header band ──
    doc.rect(0, 0, doc.page.width, 90).fill(BRAND_GREEN);
    doc.fillColor('#fff').fontSize(20).font('Helvetica-Bold').text('AgriConnect', PAGE_LEFT, 30);
    doc.fontSize(10).font('Helvetica').text('Pakistan Agricultural Marketplace', PAGE_LEFT, 55);

    doc.fillColor('#111').fontSize(16).font('Helvetica-Bold').text(spec.documentTitle, PAGE_LEFT, 112);
    doc.fontSize(10).font('Helvetica').fillColor('#555').text(
      `${spec.documentNumber}   ·   Issued ${spec.issuedAt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}`,
      PAGE_LEFT, 133,
    );

    let y = 168;

    // ── From / To ──
    doc.fontSize(8.5).fillColor('#999').font('Helvetica-Bold').text('FROM', PAGE_LEFT, y);
    doc.text('TO', 320, y);
    y += 14;
    doc.fontSize(10).fillColor('#111').font('Helvetica-Bold');
    spec.fromLines.forEach((line, i) => doc.text(line, PAGE_LEFT, y + i * 14, { width: 240 }));
    spec.toLines.forEach((line, i) => doc.text(line, 320, y + i * 14, { width: 225 }));
    y += Math.max(spec.fromLines.length, spec.toLines.length) * 14 + 24;

    // ── Meta rows ──
    if (spec.meta?.length) {
      spec.meta.forEach(([k, v]) => {
        doc.font('Helvetica').fontSize(9.5).fillColor('#666').text(`${k}:`, PAGE_LEFT, y, { continued: true, width: 150 });
        doc.font('Helvetica-Bold').fillColor('#111').text(` ${v}`);
        y += 16;
      });
      y += 8;
    }

    // ── Line items table ──
    doc.moveTo(PAGE_LEFT, y).lineTo(PAGE_RIGHT, y).strokeColor('#DDD').stroke();
    y += 10;
    doc.font('Helvetica-Bold').fontSize(9.5).fillColor('#111');
    doc.text('DESCRIPTION', PAGE_LEFT, y);
    doc.text('AMOUNT (PKR)', 385, y, { width: 160, align: 'right' });
    y += 16;
    doc.moveTo(PAGE_LEFT, y).lineTo(PAGE_RIGHT, y).strokeColor('#DDD').stroke();
    y += 10;

    doc.font('Helvetica').fontSize(10).fillColor('#333');
    spec.lineItems.forEach((item) => {
      doc.text(item.label, PAGE_LEFT, y, { width: 320 });
      if (item.amount !== undefined) {
        doc.text(formatAmount(item.amount), 385, y, { width: 160, align: 'right' });
      }
      y += 20;
    });

    if (spec.totalAmount !== undefined) {
      y += 6;
      doc.moveTo(300, y).lineTo(PAGE_RIGHT, y).strokeColor('#111').stroke();
      y += 10;
      doc.font('Helvetica-Bold').fontSize(11.5).fillColor('#111');
      doc.text(spec.totalLabel || 'TOTAL', PAGE_LEFT, y);
      doc.text(`₨ ${formatAmount(spec.totalAmount)}`, 385, y, { width: 160, align: 'right' });
      y += 32;
    }

    if (spec.footerNote) {
      doc.font('Helvetica-Oblique').fontSize(9).fillColor('#888').text(spec.footerNote, PAGE_LEFT, y, { width: PAGE_RIGHT - PAGE_LEFT });
    }

    doc.fontSize(8).fillColor('#AAA').font('Helvetica')
      .text('Generated by AgriConnect — this is a system-generated document.', PAGE_LEFT, 780, { width: PAGE_RIGHT - PAGE_LEFT, align: 'center' });

    doc.end();
  });
}

function formatAmount(n: number): string {
  return n.toLocaleString('en-PK', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
